version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  open-pull-requests-limit: 9999
  schedule:
    interval: daily
  assignees:
    - marekdedic
- package-ecosystem: composer
  directory: "/"
  open-pull-requests-limit: 9999
  schedule:
    interval: daily
  assignees:
    - marekdedic
